[package]
name = "kzg_verifier"
type = "lib"
authors = ["Rajesh Kanna"]
compiler_version = ">=0.22.0"

[dependencies]
bls12_381 = { tag = "v0.1.0", git = "https://github.com/RajeshRk18/noir_bls12_381.git" }
