[package]
name = "kzg_verifier"
type = "lib"
authors = ["Rajesh"]
compiler_version = ">=1.0.0"

[dependencies]
bignum = { tag = "v0.10.0", git = "https://github.com/noir-lang/noir-bignum" }
noir_bigcurve = { tag = "v0.14.0", git = "https://github.com/noir-lang/noir_bigcurve" }
bls12_381 = { tag = "main", git = "https://github.com/critesjosh/noir-bls-signature" }
